CREATE USER 'idpuser'@'%' IDENTIFIED BY '__IDP_USER_PASSWORD__';

CREATE DATABASE JavaIdp;

GRANT CREATE, INSERT, UPDATE, DELETE, SELECT, REFERENCES, ALTER on JavaIdp.* to 'idpuser'@'%';

USE JavaIdp;