services:
  # mysql:
  #   image: mysql:8.0
  #   volumes: 
  #     - ./MySQL/:/docker-entrypoint-initdb.d
  #     - mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     IDP_USER_PASSWORD: ${IDP_USER_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 20s
  postgres:
    image: postgres:17
    volumes: 
      - ./PostgreSQL/:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      IDP_USER_PASSWORD: ${IDP_USER_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s

# TODO set up connection to dedicated docker network for overall project
networks:
  idp-network:

volumes:
  mysql-data:
  postgres-data: