services:
  idp-server:
    image: sourceware-labs/sourceware-lab-idp:latest
    container_name: sourceware-lab-idp
    ports:
      - "8080:8080"
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${IDP_USER_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_FROM_EMAIL=${AWS_FROM_EMAIL}
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    volumes: 
      - ./MySQL/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      IDP_USER_PASSWORD: ${IDP_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s

# TODO set up connection to dedicated docker network for overall project
networks:
  idp-network:

volumes:
  mysql-data: